### ISSUE TITLE
ImportError: cannot import name 'SoftwareCompany' from 'metagpt.software_company'

### ISSUE THREAD

**Issue by SheldonLiu0412** [geekan/MetaGPT-docs#125]
ImportError: cannot import name 'SoftwareCompany' from 'metagpt.software_company'

All code：from metagpt.software_company import SoftwareCompany
from metagpt.roles import ProjectManager, ProductManager, Architect, Engineer
async def  startup(idea: str, investment: float = 3.0, n_round: int = 5):
    """Run a startup. Be a boss."""
    company = SoftwareCompany()
    company.hire([ProductManager(), Architect(), ProjectManager(), Engineer()])
    company.invest(investment)
    company.start_project(idea)
    await company.run(n_round=n_round)
metagpt version：0.8.0
python version：3.10.14

**Comment by seehi** [comment]
Where did you see the code? The document might not be updated; there is no SoftwareCompany in [software_company.py](https://github.com/geekan/MetaGPT/blob/v0.8-release/metagpt/software_company.py#L45) in 0.8.0.

**Comment by SheldonLiu0412** [comment]
In a langchain learning instance, the code may be out of date
